chore(deps): bump the major group with 2 updates (#2431)
Bumps the major group with 2 updates:
[vue-i18n](https://github.com/intlify/vue-i18n/tree/HEAD/packages/vue-i18n)
and [commander](https://github.com/tj/commander.js).

Updates `vue-i18n` from 10.0.5 to 11.0.1
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/intlify/vue-i18n/releases">vue-i18n's
releases</a>.</em></p>
<blockquote>
<h2>v11.0.1</h2>
<!-- raw HTML omitted -->
<h2>What's Changed</h2>
<h3>⚡ Improvement Features</h3>
<ul>
<li>fix: v-t custom directive warning when it will run by <a
href="https://github.com/kazupon"><code>@​kazupon</code></a> in <a
href="https://redirect.github.com/intlify/vue-i18n/pull/2057">intlify/vue-i18n#2057</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/intlify/vue-i18n/compare/v11.0.0...v11.0.1">https://github.com/intlify/vue-i18n/compare/v11.0.0...v11.0.1</a></p>
<h2>v11.0.0</h2>
<!-- raw HTML omitted -->
<p>We are excited to announce the release of Vue I18n v11.
We had many contributors.</p>
<p>Thanks for your contributing ❤️</p>
<h1>Summary</h1>
<h2>Deprecate Legacy API mode</h2>
<p>The Legacy API mode was the API mode compatible with v8 for Vue 2.
When v9 was released, the Legacy API was provided to smooth the
migration from v8 to v9.</p>
<p>Legacy API mode will be deprecated in v11, as previous vue-i18n
releases have already provided the following to support migration to
Composition API mode</p>
<ul>
<li>Migration from Legacy API mode to Composition API mode, see the <a
href="https://vue-i18n.intlify.dev/guide/migration/vue3.html">docs</a></li>
<li>Composition API usage, see the <a
href="https://vue-i18n.intlify.dev/guide/advanced/composition.html">docs</a></li>
</ul>
<p>For compatibility, Legacy API mode still works in v11, but will be
removed entirely in v12, so Legacy API mode will not work after that
version.</p>
<h2>Deprecate Custom Directive <code>v-t</code></h2>
<p>The advantage of <code>v-t</code> was that it could optimize
performance using the vue compiler transform and the pre-translation of
<code>vue-i18n-extension</code>.</p>
<p>This feature was supported from Vue 2.
About details see the blog <a
href="https://medium.com/@kazu_pon/performance-optimization-of-vue-i18n-83099eb45c2d">article</a></p>
<p>In Vue 3, due to the Composition API, the pre-translation of <a
href="https://github.com/intlify/vue-i18n-extensions"><code>vue-i18n-extension</code></a>
is now limited only for global scope.</p>
<p>In addition, Vue 3 Virtual DOM optimization has been introduced, and
the optimization provided by <code>vue-i18n-extension</code> is no
longer very effective. We need to require settings for SSR, the benefits
of using <code>v-t</code> have disappeared. And DX of templates using
<code>v-t</code> is not good. Custom directives do not work with key
completion in editors (e.g. vscode).</p>
<p>For compatibility, <code>v-t</code> mode still works in v11, but will
be removed entirely in v12, so <code>v-t</code> will not work after that
version.</p>
<h2>Drop <code>tc</code> and <code>$tc</code> for Legacy API mode</h2>
<p>These APIs had already deprecated in warning about being dropped in
v11. docs <a
href="https://vue-i18n.intlify.dev/guide/migration/breaking10.html#deprecate-tc-and-tc-for-legacy-api-mode">says</a></p>
<h2>Vue I18n maintenance Status</h2>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/intlify/vue-i18n/blob/master/CHANGELOG.md">vue-i18n's
changelog</a>.</em></p>
<blockquote>
<h1>v11.0.1 (2024-12-26T07:40:58Z)</h1>
<p>This changelog is generated by <a
href="https://github.com/intlify/vue-i18n/releases/tag/v11.0.1">GitHub
Releases</a></p>
<!-- raw HTML omitted -->
<h2>What's Changed</h2>
<h3>⚡ Improvement Features</h3>
<ul>
<li>fix: v-t custom directive warning when it will run by <a
href="https://github.com/kazupon"><code>@​kazupon</code></a> in <a
href="https://redirect.github.com/intlify/vue-i18n/pull/2057">intlify/vue-i18n#2057</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/intlify/vue-i18n/compare/v11.0.0...v11.0.1">https://github.com/intlify/vue-i18n/compare/v11.0.0...v11.0.1</a></p>
<h1>v11.0.0 (2024-12-24T15:01:00Z)</h1>
<p>This changelog is generated by <a
href="https://github.com/intlify/vue-i18n/releases/tag/v11.0.0">GitHub
Releases</a></p>
<!-- raw HTML omitted -->
<h2>What's Changed</h2>
<h3>Deprecate Legacy API mode</h3>
<p>The Legacy API mode was the API mode compatible with v8 for Vue 2.
When v9 was released, the Legacy API was provided to smooth the
migration from v8 to v9.</p>
<p>Legacy API mode will be deprecated in v11, as previous vue-i18n
releases have already provided the following to support migration to
Composition API mode</p>
<ul>
<li>Migration from Legacy API mode to Composition API mode, see the <a
href="https://vue-i18n.intlify.dev/guide/migration/vue3.html">docs</a></li>
<li>Composition API usage, see the <a
href="https://vue-i18n.intlify.dev/guide/advanced/composition.html">docs</a></li>
</ul>
<p>For compatibility, Legacy API mode still works in v11, but will be
removed entirely in v12, so Legacy API mode will not work after that
version.</p>
<h3>Deprecate Custom Directive <code>v-t</code></h3>
<p>The advantage of <code>v-t</code> was that it could optimize
performance using the vue compiler transform and the pre-translation of
<code>vue-i18n-extension</code>.</p>
<p>This feature was supported from Vue 2.
About details see the blog <a
href="https://medium.com/@kazu_pon/performance-optimization-of-vue-i18n-83099eb45c2d">article</a></p>
<p>In Vue 3, due to the Composition API, the pre-translation of <a
href="https://github.com/intlify/vue-i18n-extensions"><code>vue-i18n-extension</code></a>
is now limited only for global scope.</p>
<p>In addition, Vue 3 Virtual DOM optimization has been introduced, and
the optimization provided by <code>vue-i18n-extension</code> is no
longer very effective. We need to require settings for SSR, the benefits
of using <code>v-t</code> have disappeared. And DX of templates using
<code>v-t</code> is not good. Custom directives do not work with key
completion in editors (e.g. vscode).</p>
<p>For compatibility, <code>v-t</code> mode still works in v11, but will
be removed entirely in v12, so <code>v-t</code> will not work after that
version.</p>
<h3>Drop <code>tc</code> and <code>$tc</code> for Legacy API mode</h3>
<p>These APIs had already deprecated in warning about being dropped in
v11. docs <a
href="https://vue-i18n.intlify.dev/guide/migration/breaking10.html#deprecate-tc-and-tc-for-legacy-api-mode">says</a></p>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/intlify/vue-i18n/commit/49c0e18541e19d1263a3074b778ebb24bc596c9c"><code>49c0e18</code></a>
release: v11.0.1</li>
<li><a
href="https://github.com/intlify/vue-i18n/commit/2b986621ad04b10825dc61db18a82137470c3278"><code>2b98662</code></a>
release: v11.0.0</li>
<li><a
href="https://github.com/intlify/vue-i18n/commit/61cea89fbe1236cb26c90e27abc156500050e2f8"><code>61cea89</code></a>
release: v11.0.0-rc.1</li>
<li><a
href="https://github.com/intlify/vue-i18n/commit/3808ae72ac49348a2e050d892ada64d244b47250"><code>3808ae7</code></a>
release: v11.0.0-beta.2</li>
<li><a
href="https://github.com/intlify/vue-i18n/commit/d10a4ef23653518e94bab5dcb4dde21e58e791d2"><code>d10a4ef</code></a>
release: v11.0.0-beta.1</li>
<li><a
href="https://github.com/intlify/vue-i18n/commit/3882d024ae64c9a624a7db788d8ed5419d588cab"><code>3882d02</code></a>
breaking: drop <code>$tc</code> and <code>tc</code> (<a
href="https://github.com/intlify/vue-i18n/tree/HEAD/packages/vue-i18n/issues/2017">#2017</a>)</li>
<li><a
href="https://github.com/intlify/vue-i18n/commit/2a44e212bba79f4b1568b1ac5abaa5bce9e2d3a1"><code>2a44e21</code></a>
release: v11.0.0-beta.0</li>
<li><a
href="https://github.com/intlify/vue-i18n/commit/ea528c4374846d9f6306176c2eb9fc54f3d52809"><code>ea528c4</code></a>
fix: <code>tm</code> function should accept
<code>DefineLocaleMessage</code> key type (<a
href="https://github.com/intlify/vue-i18n/tree/HEAD/packages/vue-i18n/issues/2014">#2014</a>)</li>
<li>See full diff in <a
href="https://github.com/intlify/vue-i18n/commits/v11.0.1/packages/vue-i18n">compare
view</a></li>
</ul>
</details>
<br />

Updates `commander` from 12.1.0 to 13.0.0
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/tj/commander.js/releases">commander's
releases</a>.</em></p>
<blockquote>
<h2>v13.0.0</h2>
<h3>Added</h3>
<ul>
<li>support multiple calls to <code>.parse()</code> with default
settings (<a
href="https://redirect.github.com/tj/commander.js/issues/2299">#2299</a>)</li>
<li>add <code>.saveStateBeforeParse()</code> and
<code>.restoreStateBeforeParse()</code> for use by subclasses (<a
href="https://redirect.github.com/tj/commander.js/issues/2299">#2299</a>)</li>
<li>style routines like <code>styleTitle()</code> to add color to help
using <code>.configureHelp()</code> or Help subclass (<a
href="https://redirect.github.com/tj/commander.js/issues/2251">#2251</a>)</li>
<li>color related support in <code>.configureOutput()</code> for
<code>getOutHasColors()</code>, <code>getErrHasColors()</code>, and
<code>stripColor()</code> (<a
href="https://redirect.github.com/tj/commander.js/issues/2251">#2251</a>)</li>
<li>Help property for <code>minWidthToWrap</code> (<a
href="https://redirect.github.com/tj/commander.js/issues/2251">#2251</a>)</li>
<li>Help methods for <code>displayWidth()</code>,
<code>boxWrap()</code>, <code>preformatted()</code> et al (<a
href="https://redirect.github.com/tj/commander.js/issues/2251">#2251</a>)</li>
</ul>
<h3>Changed</h3>
<ul>
<li><em>Breaking</em>: excess command-arguments cause an error by
default, see migration tips (<a
href="https://redirect.github.com/tj/commander.js/issues/2223">#2223</a>)</li>
<li><em>Breaking</em>: throw during Option construction for unsupported
option flags, like multiple characters after single <code>-</code> (<a
href="https://redirect.github.com/tj/commander.js/issues/2270">#2270</a>)</li>
<li><em>Breaking</em>: throw on multiple calls to <code>.parse()</code>
if <code>storeOptionsAsProperties: true</code> (<a
href="https://redirect.github.com/tj/commander.js/issues/2299">#2299</a>)</li>
<li>TypeScript: include implicit <code>this</code> in parameters for
action handler callback (<a
href="https://redirect.github.com/tj/commander.js/issues/2197">#2197</a>)</li>
</ul>
<h3>Deleted</h3>
<ul>
<li><em>Breaking</em>: <code>Help.wrap()</code> refactored into
<code>formatItem()</code> and <code>boxWrap()</code> (<a
href="https://redirect.github.com/tj/commander.js/issues/2251">#2251</a>)</li>
</ul>
<h3>Migration Tips</h3>
<p><strong>Excess command-arguments</strong></p>
<p>It is now an error for the user to specify more command-arguments
than are expected. (<code>allowExcessArguments</code> is now false by
default.)</p>
<p>Old code:</p>
<pre lang="js"><code>program.option('-p, --port &lt;number&gt;', 'port
number');
program.action((options) =&gt; {
  console.log(program.args);
});
</code></pre>
<p>Now shows an error:</p>
<pre lang="console"><code>$ node example.js a b c
error: too many arguments. Expected 0 arguments but got 3.
</code></pre>
<p>You can declare the expected arguments. The help will then be more
accurate too. Note that declaring
new arguments will change what is passed to the action handler.</p>
<pre lang="js"><code>program.option('-p, --port &lt;number&gt;', 'port
number');
program.argument('[args...]', 'remote command and arguments'); //
expecting zero or more arguments
program.action((args, options) =&gt; {
&lt;/tr&gt;&lt;/table&gt; 
</code></pre>
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/tj/commander.js/blob/master/CHANGELOG.md">commander's
changelog</a>.</em></p>
<blockquote>
<h2>[13.0.0] (2024-12-30)</h2>
<h3>Added</h3>
<ul>
<li>support multiple calls to <code>.parse()</code> with default
settings (<a
href="https://redirect.github.com/tj/commander.js/issues/2299">#2299</a>)</li>
<li>add <code>.saveStateBeforeParse()</code> and
<code>.restoreStateBeforeParse()</code> for use by subclasses (<a
href="https://redirect.github.com/tj/commander.js/issues/2299">#2299</a>)</li>
<li>style routines like <code>styleTitle()</code> to add color to help
using <code>.configureHelp()</code> or Help subclass (<a
href="https://redirect.github.com/tj/commander.js/issues/2251">#2251</a>)</li>
<li>color related support in <code>.configureOutput()</code> for
<code>getOutHasColors()</code>, <code>getErrHasColors()</code>, and
<code>stripColor()</code> (<a
href="https://redirect.github.com/tj/commander.js/issues/2251">#2251</a>)</li>
<li>Help property for <code>minWidthToWrap</code> (<a
href="https://redirect.github.com/tj/commander.js/issues/2251">#2251</a>)</li>
<li>Help methods for <code>displayWidth()</code>,
<code>boxWrap()</code>, <code>preformatted()</code> et al (<a
href="https://redirect.github.com/tj/commander.js/issues/2251">#2251</a>)</li>
</ul>
<h3>Changed</h3>
<ul>
<li><em>Breaking</em>: excess command-arguments cause an error by
default, see migration tips (<a
href="https://redirect.github.com/tj/commander.js/issues/2223">#2223</a>)</li>
<li><em>Breaking</em>: throw during Option construction for unsupported
option flags, like multiple characters after single <code>-</code> (<a
href="https://redirect.github.com/tj/commander.js/issues/2270">#2270</a>)</li>
<li><em>Breaking</em>: throw on multiple calls to <code>.parse()</code>
if <code>storeOptionsAsProperties: true</code> (<a
href="https://redirect.github.com/tj/commander.js/issues/2299">#2299</a>)</li>
<li>TypeScript: include implicit <code>this</code> in parameters for
action handler callback (<a
href="https://redirect.github.com/tj/commander.js/issues/2197">#2197</a>)</li>
</ul>
<h3>Deleted</h3>
<ul>
<li><em>Breaking</em>: <code>Help.wrap()</code> refactored into
<code>formatItem()</code> and <code>boxWrap()</code> (<a
href="https://redirect.github.com/tj/commander.js/issues/2251">#2251</a>)</li>
</ul>
<h3>Migration Tips</h3>
<p><strong>Excess command-arguments</strong></p>
<p>It is now an error for the user to specify more command-arguments
than are expected. (<code>allowExcessArguments</code> is now false by
default.)</p>
<p>Old code:</p>
<pre lang="js"><code>program.option('-p, --port &lt;number&gt;', 'port
number');
program.action((options) =&gt; {
  console.log(program.args);
});
</code></pre>
<p>Now shows an error:</p>
<pre lang="console"><code>$ node example.js a b c
error: too many arguments. Expected 0 arguments but got 3.
</code></pre>
<p>You can declare the expected arguments. The help will then be more
accurate too. Note that declaring
new arguments will change what is passed to the action handler.</p>
<pre lang="js"><code>program.option('-p, --port &lt;number&gt;', 'port
number');
program.argument('[args...]', 'remote command and arguments'); //
expecting zero or more arguments
&lt;/tr&gt;&lt;/table&gt; 
</code></pre>
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/tj/commander.js/commit/d6bcb0b6e144d8854360a5c3c2759fadf0e4edb3"><code>d6bcb0b</code></a>
13.0.0</li>
<li><a
href="https://github.com/tj/commander.js/commit/fa9e5eddb8b91b242a0aba5e2e5272547772e436"><code>fa9e5ed</code></a>
Update release date</li>
<li><a
href="https://github.com/tj/commander.js/commit/fb2c46a005e9f7796a32fcd0652d847ea39940dc"><code>fb2c46a</code></a>
Update CHANGELOG for 13.0.0 (<a
href="https://redirect.github.com/tj/commander.js/issues/2301">#2301</a>)</li>
<li><a
href="https://github.com/tj/commander.js/commit/49423a288b6561190461bf91231a18085e60dad4"><code>49423a2</code></a>
Add save/restore state to allow multiple calls to parse (<a
href="https://redirect.github.com/tj/commander.js/issues/2299">#2299</a>)</li>
<li><a
href="https://github.com/tj/commander.js/commit/497c11d83065567a3b2840bc0800d30e6ab4ed33"><code>497c11d</code></a>
Update dependencies (<a
href="https://redirect.github.com/tj/commander.js/issues/2295">#2295</a>)</li>
<li><a
href="https://github.com/tj/commander.js/commit/a8ef5cf3e1975380974ab5c4f92c26fb2c5e3209"><code>a8ef5cf</code></a>
Add informative message for missing executable on Windows (<a
href="https://redirect.github.com/tj/commander.js/issues/2291">#2291</a>)</li>
<li><a
href="https://github.com/tj/commander.js/commit/02c603ebedaec334ba9edc7c3c2e48484e2aeaf8"><code>02c603e</code></a>
Add clues about what help configuration is available to help with
searches an...</li>
<li><a
href="https://github.com/tj/commander.js/commit/37e86af4c14b22db04adfce4b05597567f207167"><code>37e86af</code></a>
Add links to CHANGELOG</li>
<li><a
href="https://github.com/tj/commander.js/commit/53fc8a4b287e063af0bd3a026cad06bf1cf07bcf"><code>53fc8a4</code></a>
Prepare for 13.0.0-0 (<a
href="https://redirect.github.com/tj/commander.js/issues/2292">#2292</a>)</li>
<li><a
href="https://github.com/tj/commander.js/commit/d355b52d2013def008e7874c14f97d4fd96ed26f"><code>d355b52</code></a>
More Help documentation (<a
href="https://redirect.github.com/tj/commander.js/issues/2282">#2282</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/tj/commander.js/compare/v12.1.0...v13.0.0">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Lars Rickert <lars.rickert@mail.schwarz>